### ISSUE TITLE
Can I use shadow with lean?

### ISSUE THREAD

**Issue by Magnum97** [cuzfrog/gradle-lean#4]
I agree that shadowJar does not do well in the minimization department; I want to try this but also need to shadow some libraries. Can I use them both? If so should lean run before or after shadowJar task?

**Comment by cuzfrog** [comment]
If what I recall is right, the plugin works at the packaging phase. It uses asm to gather the class dependencies information and remove unused classes. If some classes/packages are already reduced by whatever filter you added, it will simply skip or ignore.
